import type { PDFTool } from '../types/pdf';

export const TOOLS_REGISTRY: PDFTool[] = [
  // Organize
  {
    id: 'merge-pdf',
    name: 'Merge PDF',
    shortName: 'Merge',
    description: 'Combine multiple PDF documents into a single organized file in seconds.',
    category: 'organize',
    iconName: 'Layers',
    intents: ['combine', 'merge', 'join', 'stitch', 'unite', 'put together', 'multiple files'],
    processingMode: 'local',
    badge: 'Popular',
    popular: true,
  },
  {
    id: 'split-pdf',
    name: 'Split & Extract',
    shortName: 'Split',
    description: 'Separate one page or an entire set of pages into standalone PDF files.',
    category: 'organize',
    iconName: 'Scissors',
    intents: ['split', 'cut', 'extract', 'separate', 'break apart', 'extract pages', 'remove page'],
    processingMode: 'local',
    popular: true,
  },
  {
    id: 'reorder-pages',
    name: 'Organize Pages',
    shortName: 'Organize',
    description: 'Sort, reorder, rotate, duplicate, or delete individual pages visually.',
    category: 'organize',
    iconName: 'LayoutGrid',
    intents: ['reorder', 'rotate', 'delete page', 'duplicate', 'reverse', 'sort pages', 'move pages'],
    processingMode: 'local',
    popular: true,
  },
  {
    id: 'rotate-pdf',
    name: 'Rotate Pages',
    shortName: 'Rotate',
    description: 'Rotate upside-down or sideways pages clockwise or counterclockwise.',
    category: 'organize',
    iconName: 'RotateCw',
    intents: ['rotate', 'turn', 'orientation', 'upside down', 'landscape', 'portrait'],
    processingMode: 'local',
  },

  // Compress & Optimize
  {
    id: 'compress-pdf',
    name: 'Compress PDF',
    shortName: 'Compress',
    description: 'Reduce PDF file size dramatically while preserving maximum visual clarity.',
    category: 'compress',
    iconName: 'Minimize2',
    intents: ['compress', 'make smaller', 'reduce size', 'shrink', 'optimize', 'under 2mb', 'email attachment'],
    processingMode: 'local',
    badge: 'Popular',
    popular: true,
  },

  // Edit & Sign
  {
    id: 'sign-pdf',
    name: 'Sign & Fill',
    shortName: 'Sign',
    description: 'Draw, type, or upload your signature and place it anywhere with dates & initials.',
    category: 'edit',
    iconName: 'PenTool',
    intents: ['sign', 'signature', 'fill and sign', 'initials', 'autograph', 'sign contract'],
    processingMode: 'local',
    badge: 'Popular',
    popular: true,
  },
  {
    id: 'annotate-pdf',
    name: 'Annotate & Draw',
    shortName: 'Annotate',
    description: 'Add freehand drawing, highlighter strokes, shapes, and comments.',
    category: 'edit',
    iconName: 'Edit3',
    intents: ['annotate', 'draw', 'highlight', 'notes', 'pen', 'markup', 'shapes'],
    processingMode: 'local',
  },
  {
    id: 'watermark-pdf',
    name: 'Watermark PDF',
    shortName: 'Watermark',
    description: 'Stamp customized text or image watermarks with precise opacity and angle.',
    category: 'edit',
    iconName: 'Stamp',
    intents: ['watermark', 'stamp', 'confidential', 'draft', 'copyright', 'branding'],
    processingMode: 'local',
    popular: true,
  },
  {
    id: 'page-numbers',
    name: 'Page Numbers',
    shortName: 'Numbers',
    description: 'Insert dynamic page numbering, headers, and footers with custom styling.',
    category: 'edit',
    iconName: 'Hash',
    intents: ['page numbers', 'paginate', 'headers', 'footers', 'numbering', 'number pages'],
    processingMode: 'local',
  },

  // Convert
  {
    id: 'pdf-to-images',
    name: 'PDF to Images',
    shortName: 'To Images',
    description: 'Convert every PDF page into crystal-clear PNG, JPG, or WebP images.',
    category: 'convert',
    iconName: 'Image',
    intents: ['turn into images', 'convert to jpg', 'pdf to png', 'extract pictures', 'photo', 'render pages'],
    processingMode: 'local',
    popular: true,
  },
  {
    id: 'images-to-pdf',
    name: 'Images to PDF',
    shortName: 'From Images',
    description: 'Transform multiple images or photo scans into a clean, uniform PDF book.',
    category: 'convert',
    iconName: 'FileImage',
    intents: ['jpg to pdf', 'images to pdf', 'photos to pdf', 'scan photos', 'png to pdf'],
    processingMode: 'local',
    popular: true,
  },
  {
    id: 'extract-text',
    name: 'Extract Text',
    shortName: 'Extract',
    description: 'Extract raw text, markdown content, and structural data from your document.',
    category: 'convert',
    iconName: 'FileText',
    intents: ['extract text', 'copy text', 'get text', 'turn to text', 'export txt'],
    processingMode: 'local',
  },

  // Security & Privacy
  {
    id: 'protect-pdf',
    name: 'Protect & Encrypt',
    shortName: 'Protect',
    description: 'Lock your sensitive document with strong password encryption and permission controls.',
    category: 'security',
    iconName: 'Lock',
    intents: ['password', 'protect', 'encrypt', 'lock', 'secure', 'restrict printing', 'restrict copying'],
    processingMode: 'local',
    popular: true,
  },
  {
    id: 'unlock-pdf',
    name: 'Unlock PDF',
    shortName: 'Unlock',
    description: 'Remove passwords and permissions restrictions from protected PDFs you own.',
    category: 'security',
    iconName: 'Unlock',
    intents: ['unlock', 'remove password', 'decrypt', 'unprotect', 'remove security'],
    processingMode: 'local',
  },
  {
    id: 'redact-pdf',
    name: 'Redact & Blackout',
    shortName: 'Redact',
    description: 'Permanently remove sensitive text, numbers, and private info with secure flattening.',
    category: 'security',
    iconName: 'EyeOff',
    intents: ['redact', 'blackout', 'hide information', 'censor', 'remove ssn', 'sanitize private data'],
    processingMode: 'local',
    badge: 'Security',
    popular: true,
  },
  {
    id: 'metadata-scrubber',
    name: 'Sanitize Metadata',
    shortName: 'Sanitize',
    description: 'Inspect author, creation date, and software metadata, or scrub them clean.',
    category: 'security',
    iconName: 'ShieldCheck',
    intents: ['metadata', 'sanitize', 'scrub', 'remove author', 'clean document', 'inspect info'],
    processingMode: 'local',
  },

  // OCR & Analyze
  {
    id: 'ocr-pdf',
    name: 'OCR & Make Searchable',
    shortName: 'OCR',
    description: 'Convert scanned image PDFs into fully searchable, selectable text documents locally.',
    category: 'ocr',
    iconName: 'ScanText',
    intents: ['ocr', 'scan', 'searchable', 'recognize text', 'unsearchable', 'scanned pdf'],
    processingMode: 'local',
    badge: 'AI/OCR',
    popular: true,
  },
  {
    id: 'compare-pdf',
    name: 'Compare Documents',
    shortName: 'Compare',
    description: 'Visually compare two PDF versions side-by-side with synchronized scrolling.',
    category: 'organize',
    iconName: 'GitCompare',
    intents: ['compare', 'difference', 'diff', 'side by side', 'changes', 'version comparison'],
    processingMode: 'local',
    popular: true,
  },

  // AI Document Intelligence
  {
    id: 'ai-chat',
    name: 'AI Document Studio',
    shortName: 'AI Studio',
    description: 'Chat with PDF, extract action items, summarize key points, and analyze contracts.',
    category: 'ai',
    iconName: 'Sparkles',
    intents: ['chat with pdf', 'summarize', 'summary', 'ask questions', 'key points', 'analyze contract', 'ai'],
    processingMode: 'hybrid',
    badge: 'Smart',
    popular: true,
  },
];

export const CATEGORY_LABELS: Record<string, string> = {
  all: 'All Tools',
  organize: 'Organize',
  edit: 'Edit & Sign',
  convert: 'Convert',
  compress: 'Compress',
  security: 'Security & Privacy',
  ocr: 'OCR & Scan',
  ai: 'AI Studio',
};
